# Default configuration file for DiSky
# If you need more config options, ask us on Discord!
# > LINKS <
# Discord: https://disky.itsthesky.info/?page=discord
# Docs: https://disky.itsthesky.info/?page=docs

# THIS IS A BETA FEATURE !!!
# READ THE WIKI BEFORE ENABLING !!!
# SLASH COMMAND WIKI: https://github.com/SkyCraft78/DiSky/wiki/Slash-Commands
SlashCommand:
  Enabled: false
  # SlashCommands take like an hour to be updated on Discord.
  # However, we can send multiple command at once, and all of them will be updated.
  # If false, single command builders can't be registered, needs a list of commands.
  AllowSingle: false

# This is for handling Discord & DiSky errors.
# It will enable the print stack (advanced debug)
# for specific errors. Only enable this if a support
# member asks you to do so :)
HandleErrors:
  NullPointerException: false
  InsufficientPermissionException: false
