name: DiSky
version: 1.8.1
main: info.itsthesky.DiSky.DiSky
author: ItsTheSky
description: Skript addon which allow you to interact with Discord through Skript.
website: https://disky.itsthesky.info/
softdepend:
  - Skript