name: DiSky
version: 1.8
main: info.itsthesky.DiSky.DiSky
author: ItsTheSky
description: Skript addon which allows you to interact with Discord through Skript.
website: https://disky.itsthesky.info/
softdepend:
  - Skript
